### ISSUE TITLE
I want to contribute to your project

### ISSUE THREAD

**Issue by steemrcp** [tyraelll/PHP-upvote-comment-bot#6]
Hi, Sorry this isn't the right place to contact you about this because it isn't an issues but i'm only doing this because i can't seem to find any contact detail on this project. I will like to contribute to your project and want to be sure you will be willing to merge my pull requests. Thanks

**Comment by tyraelll** [comment]
Hey @steemrcp. Your contributions will be welcomed gladly. In which point you want to improve the system ?

**Comment by steemrcp** [comment]
Thanks. I have noticed the project accepts WIF key for authentication and
stores it in a cookie. We can make it a well trusted site for users to make
use of it by using steemconnect for authentication.

I also want to add a feature where a users can add username of steemit
accounts to a "monitor" list so they can quick access posts of these
username in order to upvote or comment.

I can also add features for automatic upvote of posts added to a "monitor"
list.

Hope these features are OK.

Thanks once again

**Comment by tyraelll** [comment]
Perfect! Will be waiting for those

**Comment by steemrcp** [comment]
Great.

Please could you briefly explain the functions of "User List Upvote" and
"Tag List Upvote"

Thanks

**Comment by steemrcp** [comment]
Also, please can you kindly provide me the link to a post where you
introduced steem voter on utopian or steemit so i can use it as reference.

**Comment by steemrcp** [comment]
Hi

I just submitted two pull requests. Kindly review

Thanks

**Comment by tyraelll** [comment]
Merged. Thanks for your contribution.
